### ISSUE TITLE
Some emulators close or reset console

### ISSUE THREAD

**Issue by rpjx8086** [Ruka-CFW/rk3128-cfw#60] opened 2021-09-27 21:12 UTC
Emulators like:
Master System (close content after play for some time)
Playstation (crash after change some configs in some games)
SNES (close content or reboot after some time playing)
GBA (reboot)
Closing content, crash ou Reboot console.

Another emulators run very well.

**Comment by fakemaria** [comment] 2021-09-28 06:52
> Emulators like:
> Master System (close content after play for some time)
> Playstation (crash after change some configs in some games)
> SNES (close content or reboot after some time playing)
> GBA (reboot)
> Closing content, crash ou Reboot console.
> 
> Another emulators run very well.

Never had this problem and no one of the 3000 users who tested it reported it.
Do you mind to include the exact repro steps ? yours is too broad and I can’t test without that detailed information. Thanks!!!

**Comment by alpgarcia** [comment] 2021-09-28 07:42
Please @rpjx8086 fill in the bug template when reporting a bug. The template guides you to provide enough information so other users can test and reproduce the problem. Find a copy of the template right below:

**Describe the bug**
A clear and concise description of what the bug is.

**Custom Firmware version:** [e.g. v3.0 Alpha 1]

**Console (please complete the following information):**
 - Brand: [e.g. Powkiddy]
 - Model: [e.g. a12, a13]
 - Version: [e.g. 2]
 - Mods: [e.g. IPS screen]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by rpjx8086** [comment] 2021-10-02 20:11
Thanks for the answer, and sorry for my fault.

PS5000 model B
ruka v3 beta 1
Oled screen

Well I solved the problems just flash again my console. I believe what the first time some thing crashes in flash, but now is run very well, all emulators. Thanks for this.

But I have two questions:

How to save the configs like folders to search roms permanently, bcz I ever make all configs again.

I don´t know why but memory cards not works to save the psx games, I'm using the bios scph1001.bin, is it a bug or some restriction of fw to access my sd like happen in raspberry?

Thanks a lot

**Comment by fakemaria** [comment] 2021-10-02 20:18
@rpjx8086 Im not sure im following you,but seems to be retroarch questions, like configurations and usage of the emulators which are out of scope of the proyect.

https://t.me/powkiddyEng
You can visit the community on Telegram and make your questions there,Im pretty sure somebody can help you with all of that questions!!!

ps: closing the bug

**Closed** 2021-10-03 08:54 UTC
Labels: bug
