### ISSUE TITLE
PS5000 "no cores available" (not exactly a bug)

### ISSUE THREAD

**Issue by yuricraz** [Ruka-CFW/rk3128-cfw#61] opened 2021-10-09 14:00 UTC
i've followed the guide of the PS5000 and installed the CFW just fine, but i cant make it run any roms at all, the console just keep giving me the "no core availables" message when i try to run any roms (i've put the bios on the correct folder).

i've try to flash the olders releases but the results are the same.

maybe i'm too dumb and i'm letting pass something, but i would be very grateful with some help.

![PS5000 no cores available](https://user-images.githubusercontent.com/92217373/136660907-66b87bac-6a6e-4cc0-ad31-7f6aaac03ea1.jpeg)

**Comment by fakemaria** [comment] 2021-10-09 14:03
Ive replied this morning on telegram. Im closing this but as this is not a bug and is related with how to use Retroarch,which is out of the proyect scope

**Closed by fakemaria** 2021-10-09 14:03 UTC
Labels: bug

**Comment by yuricraz** [comment] 2021-10-09 14:07
i'm not on telegram, sorry. but i dont know who else to ask for, i've tried to search for a solution but can't solve it on my own, can't u help? please.

**Comment by yuricraz** [comment] 2021-10-09 14:13
okay, i'll try thanks for the attention and sorry for bothering u.
