### ISSUE TITLE
Não acho o arquivo ruka_ps5000_universal_v3.0_beta_2_20210827.img

### ISSUE THREAD

**Issue by BinnoBR** [Ruka-CFW/rk3128-cfw#59] opened 2021-09-13 02:33 UTC
Não achei o arquivo para flashear, e por isso não funciona.

**Custom Firmware version:** [v3.0 beta 2]

**Console (PS5000):**
 - Brand: [Powkiddy]
 - Model: [PS5000]

**Comment by alpgarcia** [comment] 2021-09-13 07:28
All the files are available on the release page and linked from the [installation steps](https://github.com/Ruka-CFW/rk3128-cfw/blob/main/doc/install_ps5000.md): https://github.com/Ruka-CFW/rk3128-cfw/releases/tag/v3.0_beta_2

**Comment by BinnoBR** [comment] 2021-09-15 12:04
Bom dia pessoal!!
Verifiquei o procedimento e a instalação foi concluída no aparelho.
O arquivo que eu não achava, na verdade acho que já estava junto...

O que acontece agora é que o aparelho não encontra o cartão SD.
Eu usei o de 64GB que vem com ele, um de 16GB que veio com um RS-97 
que morreu, e com um de 4GB que veio com um Sup M3 e não funciona, 
da uma tela azul: " Loading SDCARD block 1; Read Error a ".

PLEAS, HELP MEEEEEE!!!!!!

**Comment by alpgarcia** [comment] 2021-09-15 14:41
That seems a problem with the console's card reader, not a problem with the custom firmware.

How do your sd card contents look like?

It should be something like:
```
.config
.config/retroarch
.config/retroarch/cores 
rukafs
configs
logs
roms
roms/bios
```

BTW, I'm removing the bug label as this is not a bug.

**Comment by BinnoBR** [comment] 2021-09-18 18:57
Está assim:

-PASTAS
.config
configs
logs
roms

-ARQUIVO
rukafs

Pode ser isso então... Posso apenas criar as pastas e 
funciona ou teria que baixar novamente o CFW?

**Comment by BinnoBR** [comment] 2021-09-18 19:03
Olhei aqui e dentro da pasta-.config tem a pasta-retroarch e dentro tem a pasta-cores.
Dentro da pasta-roms tem a pasta-bios também.

**Comment by alpgarcia** [comment] 2021-09-18 21:51
The error you get means the SD card was not found. So there is a problem with your card or with the console's card reader. Try a different SD card. Format the card before copying the files to make sure that's not the problem.

Further than that I fear I can't help you too much as It is not a problem of the custom firmware.

**Comment by BinnoBR** [comment] 2021-09-19 22:31
Yes, yes. I see this... I make a download and format this before, but don't rum... I am :'( . My game or SD is brookin... I don't know I make... You have a idea I make about this??

**Comment by alpgarcia** [comment] 2021-09-19 23:36
Try flashing your OFW backup again to confirm the SD reader doesn't work.

As this is not a problem with the CFW I recommend you to ask in any of the [public chats related to this console](https://discord.com/channels/529983248114122762/859850710279651348).

**Comment by BinnoBR** [comment] 2021-09-20 03:55
How do I return with the backup? 
And where do I find the original Dump of the SD? 
I couldn't back up the card.

**Comment by fakemaria** [comment] 2021-09-20 08:45
@BinnoBR use the backup you did before flashing.
open android tools console and write that
WL 0x0 backup.img

Please try to keep the communication in English, use the google translate if you don´t feel comfortable with that. Further comments won´t be replied if are not in English.
Thanks!

**Comment by BinnoBR** [comment] 2021-09-21 14:50
Yes!! I see this... My englis not is so much good, but I want help and in englis is more easy to have return...
I make this, naw I need a dump of SD card... Your have a link to download?

**Comment by fakemaria** [comment] 2021-09-21 15:08
> Yes!! I see this... My englis not is so much good, but I want help and in englis is more easy to have return...
> I make this, naw I need a dump of SD card... Your have a link to download?

I can provide a dump of the original sdcard(without roms,bios or other non legit content). Ill update this thread!

**Comment by fakemaria** [comment] 2021-09-21 17:12
@BinnoBR send me a message on telegram and I will send you the sdcard structure

**Comment by BinnoBR** [comment] 2021-09-23 12:38
I dont use Telegram, but I sent to? I see a acout to sent... Thanks!!

**Comment by BinnoBR** [comment] 2021-09-24 12:36
I installed Telegram. How to send to you?

**Comment by fakemaria** [comment] 2021-09-24 12:37
Search the username @fakemaria

**Comment by BinnoBR** [comment] 2021-09-24 12:39
Thanks! I send a mensage...

**Comment by BinnoBR** [comment] 2021-09-24 12:43
Return this mensage to me:
I'm sorry, you can't send messages to mutual contacts right now.

**Comment by BinnoBR** [comment] 2021-09-24 12:56
Pleas, add and send to me... +55 (32) 98424-7468

**Comment by BinnoBR** [comment] 2021-09-27 02:35
Thanks!! Now rum... If have another upgrade, I rum another time...

**Comment by fakemaria** [comment] 2021-09-27 15:25
Glad to hear that. Closing the issue!

**Closed by fakemaria** 2021-09-27 15:25 UTC
Labels: PS5000
